# Generated by Django 4.2.8 on 2024-03-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itedata',
            name='ros_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ros_time'),
        ),
    ]
