# Generated by Django 4.2.8 on 2024-03-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0002_alter_itedata_ros_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itedata',
            name='fn',
            field=models.IntegerField(blank=True, null=True, verbose_name='fn'),
        ),
    ]
