# Generated by Django 4.2.8 on 2024-03-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0004_alter_itedata_cfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itedata',
            options={'verbose_name': 'ite数据', 'verbose_name_plural': 'ite数据管理'},
        ),
        migrations.AlterModelOptions(
            name='runningdata',
            options={'verbose_name': '运行数据', 'verbose_name_plural': '运行数据管理'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': '站点', 'verbose_name_plural': '站点数据管理'},
        ),
        migrations.AlterModelOptions(
            name='wifidata',
            options={'verbose_name': 'wifi数据', 'verbose_name_plural': 'wifi数据管理'},
        ),
        migrations.AlterField(
            model_name='itedata',
            name='alias',
            field=models.CharField(max_length=50, verbose_name='车厢号'),
        ),
        migrations.AlterField(
            model_name='itedata',
            name='rsrp',
            field=models.FloatField(verbose_name='信号强度'),
        ),
        migrations.AlterField(
            model_name='runningdata',
            name='alias',
            field=models.CharField(max_length=50, verbose_name='车厢号'),
        ),
        migrations.AlterField(
            model_name='wifidata',
            name='alias',
            field=models.CharField(max_length=50, verbose_name='车厢号'),
        ),
    ]
