# Generated by Django 4.2.8 on 2024-03-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0005_alter_itedata_options_alter_runningdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('alias', models.CharField(max_length=50, verbose_name='车厢号')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('write_time', models.DateTimeField(verbose_name='写入时间')),
                ('freq', models.IntegerField(verbose_name='频率')),
                ('gain', models.IntegerField(blank=True, null=True, verbose_name='增益')),
                ('red', models.IntegerField(blank=True, null=True, verbose_name='红色')),
                ('blue', models.IntegerField(blank=True, null=True, verbose_name='蓝色')),
                ('bin', models.IntegerField(verbose_name='bin')),
                ('fft', models.IntegerField(blank=True, null=True, verbose_name='fft')),
                ('channel', models.IntegerField(blank=True, null=True, verbose_name='channel')),
                ('wifi_time', models.DateTimeField(verbose_name='wifi时间')),
                ('gps_time', models.DateTimeField(verbose_name='gps时间')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('rssi', models.IntegerField(verbose_name='rssi')),
                ('normal_alarm_state', models.IntegerField(verbose_name='正常报警状态')),
                ('strong_alarm_state', models.IntegerField(verbose_name='强报警状态')),
                ('ros_time', models.DateTimeField(blank=True, null=True, verbose_name='ros_time')),
                ('cnt', models.IntegerField(blank=True, null=True, verbose_name='cnt')),
                ('trans_time', models.DateTimeField(blank=True, null=True, verbose_name='trans_time')),
            ],
            options={
                'verbose_name': '光谱数据',
                'verbose_name_plural': '光谱数据管理',
                'db_table': 'tb_spectrum_data',
            },
        ),
    ]
